apiVersion: v1
appVersion: 0.5.0
description: Fission Workflows is a fast workflow engine for serverless functions
  on Kubernetes
engine: gotpl
home: http://fission.io/
keywords:
- fission
- serverless
- workflows
- coordination
- orchestration
- function-as-a-service
maintainers:
- email: erwin@platform9.com
  name: Erwin van Eyk
- email: soamvasani@platform9.com
  name: Soam Vasani
name: fission-workflows
sources:
- https://github.com/fission/fission-workflows
version: 0.5.0
